stages:
  - build
  - check

include:
  # Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest

  # Build on Linux and Windows
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      anod-args: build xdiff $ACI_TRACK_QUALIFIER
      cpus: 4
      windows: true
      save-anod-logs: true
